### ISSUE TITLE
genes service: should we consider a region-based way of doing this?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/gcv-microservices#16]
The current API for this service (which BTW doesn't seem to be on the wiki yet) takes an enumerated list of genes and returns information about the genes, most critically the location info. This works, but given that the typical use is to get this information for genes contained within a set of regions, it seems like we could probably gain some efficiency by querying by region (as the typical genome browser is wont to do, and using specialized indexing techniques to support these types of range-based feature retrieval). It may be that the redis-based implementation is sufficiently performant that we won't need to pursue this, but the thought was inspired by the fact that the calls to "genes" on the django-based version for the soybean pangenome are quite slow (presumably because there are quite a lot of genes enumerated in these calls).

**Comment by alancleary** [comment]
Since the loci of genes is part of what's being fetched from the genes service, we couldn't make region queries for micro-track genes even if we wanted to, i.e. only gene identifiers and functional annotations are initially loaded, and follow-up genes service calls are made with these identifiers.

Fortunately, Redis is a key-value store, so fetching genes by ID (their Redis key) is much more performant than the Chado implementation. That said, I have contemplated chunking these requests because of the potentially huge number of genes that can be requested/returned. I think we should spend some time using the Redis implementation, though, before implementing such optimizations.

**Comment by adf-ncgr** [comment]
Oh, I was thinking the client already knew the track region but I see now that doesn't actually make sense (and the subtle detail that the track region is labelled chr:0-0 until the genes call actually returns!)

anyway, looks like this spawned some other thought from the new issue you created, but feel free to close this one if you want.
